import ExpenseIteam from "./components/ExpenseItem";

function App() {
  const expenses = [
    {
      id: "e1",
      date: new Date(),
      title: "new car",
      amount: "RS 4cr",
      location: "delhi",
    },
    {
      id: "e1",
      date: new Date(),
      title: "decoratives",
      amount: "RS 1000",
      location: "delhi",
    },
    {
      id: "e1",
      date: new Date(),
      title: "electricity bill",
      amount: "RS 8000",
      location: "delhi",
    },
    {
      id: "e1",
      date: new Date(),
      title: "domestic props",
      amount: "RS 10000",
      location: "delhi",
    },
    {
      id: "e1",
      date: new Date(),
      title: "new car",
      amount: "RS 4cr",
      location: "delhi",
    },
    {
      id: "e1",
      date: new Date(),
      title: "decoratives",
      amount: "RS 1000",
      location: "delhi",
    },
    {
      id: "e1",
      date: new Date(),
      title: "electricity bill",
      amount: "RS 8000",
      location: "delhi",
    },
    {
      id: "e1",
      date: new Date(),
      title: "domestic props",
      amount: "RS 10000",
      location: "delhi",
    },
    {
      id: "e1",
      date: new Date(),
      title: "new car",
      amount: "RS 4cr",
      location: "delhi",
    },
    {
      id: "e1",
      date: new Date(),
      title: "decoratives",
      amount: "RS 1000",
      location: "delhi",
    },
    {
      id: "e1",
      date: new Date(),
      title: "electricity bill",
      amount: "RS 8000",
      location: "delhi",
    },
    {
      id: "e1",
      date: new Date(),
      title: "domestic props",
      amount: "RS 10000",
      location: "delhi",
    },
    {
      id: "e1",
      date: new Date(),
      title: "new car",
      amount: "RS 4cr",
      location: "delhi",
    },
    {
      id: "e1",
      date: new Date(),
      title: "decoratives",
      amount: "RS 1000",
      location: "delhi",
    },
    {
      id: "e1",
      date: new Date(),
      title: "electricity bill",
      amount: "RS 8000",
      location: "delhi",
    },
    {
      id: "e1",
      date: new Date(),
      title: "domestic props",
      amount: "RS 10000",
      location: "delhi",
    },
    {
      id: "e1",
      date: new Date(),
      title: "new car",
      amount: "RS 4cr",
      location: "delhi",
    },
    {
      id: "e1",
      date: new Date(),
      title: "decoratives",
      amount: "RS 1000",
      location: "delhi",
    },
    {
      id: "e1",
      date: new Date(),
      title: "electricity bill",
      amount: "RS 8000",
      location: "delhi",
    },
    {
      id: "e1",
      date: new Date(),
      title: "domestic props",
      amount: "RS 10000",
      location: "delhi",
    },
    {
      id: "e1",
      date: new Date(),
      title: "new car",
      amount: "RS 4cr",
      location: "delhi",
    },
    {
      id: "e1",
      date: new Date(),
      title: "decoratives",
      amount: "RS 1000",
      location: "delhi",
    },
    {
      id: "e1",
      date: new Date(),
      title: "electricity bill",
      amount: "RS 8000",
      location: "delhi",
    },
    {
      id: "e1",
      date: new Date(),
      title: "domestic props",
      amount: "RS 10000",
      location: "delhi",
    },
    {
      id: "e1",
      date: new Date(),
      title: "new car",
      amount: "RS 4cr",
      location: "delhi",
    },
    {
      id: "e1",
      date: new Date(),
      title: "decoratives",
      amount: "RS 1000",
      location: "delhi",
    },
    {
      id: "e1",
      date: new Date(),
      title: "electricity bill",
      amount: "RS 8000",
      location: "delhi",
    },
    {
      id: "e1",
      date: new Date(),
      title: "domestic props",
      amount: "RS 10000",
      location: "delhi",
    },
    {
      id: "e1",
      date: new Date(),
      title: "new car",
      amount: "RS 4cr",
      location: "delhi",
    },
    {
      id: "e1",
      date: new Date(),
      title: "decoratives",
      amount: "RS 1000",
      location: "delhi",
    },
    {
      id: "e1",
      date: new Date(),
      title: "electricity bill",
      amount: "RS 8000",
      location: "delhi",
    },
    {
      id: "e1",
      date: new Date(),
      title: "domestic props",
      amount: "RS 10000",
      location: "delhi",
    },
    {
      id: "e1",
      date: new Date(),
      title: "new car",
      amount: "RS 4cr",
      location: "delhi",
    },
    {
      id: "e1",
      date: new Date(),
      title: "decoratives",
      amount: "RS 1000",
      location: "delhi",
    },
    {
      id: "e1",
      date: new Date(),
      title: "electricity bill",
      amount: "RS 8000",
      location: "delhi",
    },
    {
      id: "e1",
      date: new Date(),
      title: "domestic props",
      amount: "RS 10000",
      location: "delhi",
    },
    {
      id: "e1",
      date: new Date(),
      title: "new car",
      amount: "RS 4cr",
      location: "delhi",
    },
    {
      id: "e1",
      date: new Date(),
      title: "decoratives",
      amount: "RS 1000",
      location: "delhi",
    },
    {
      id: "e1",
      date: new Date(),
      title: "electricity bill",
      amount: "RS 8000",
      location: "delhi",
    },
    {
      id: "e1",
      date: new Date(),
      title: "domestic props",
      amount: "RS 10000",
      location: "delhi",
    },
    {
      id: "e1",
      date: new Date(),
      title: "new car",
      amount: "RS 4cr",
      location: "delhi",
    },
    {
      id: "e1",
      date: new Date(),
      title: "decoratives",
      amount: "RS 1000",
      location: "delhi",
    },
    {
      id: "e1",
      date: new Date(),
      title: "electricity bill",
      amount: "RS 8000",
      location: "delhi",
    },
    {
      id: "e1",
      date: new Date(),
      title: "domestic props",
      amount: "RS 10000",
      location: "delhi",
    },
  ];
  return (
    <div className="App">
    {

      expenses.map((p1) => { 
        return <ExpenseIteam title={p1.title} amount={p1.amount} date={p1.date} location={p1.location}/>
      })
    }
    </div>
  );
}

export default App;
